@testable import TTFreeCell
import Testing
import Foundation
import WaitWhile

private struct DealerTests {
    let subject = Dealer()
    let stats = MockStats()
    let deckFactory = MockDeckFactory()

    init() {
        services.deckFactory = deckFactory
        services.stats = stats
    }

    @Test("newDeal: creates a deck, shuffles, deals a layout, stores it in deals, returns it")
    func newDeal() async {
        let deck = MockDeck()
        deckFactory.mockDeckToReturn = deck
        deck.cardsToDeal = [Card(rank: .jack, suit: .hearts)]
        let result = await subject.newDeal()
        #expect(deck.methodsCalled == ["shuffle()", "deal()"])
        var expected = Layout()
        expected.columns[0].cards = [Card(rank: .jack, suit: .hearts)]
        #expect(result == expected)
        #expect(await subject.deals.contains(expected.tableauDescription))
    }

    @Test("newDeal: deals repeatedly until layout tableau desc is not in stats or deals")
    func newDealRepeating() async {
        let deck = MockDeck()
        deckFactory.mockDeckToReturn = deck
        deck.cardsToDeal = [
            Card(rank: .king, suit: .hearts),
            Card(rank: .jack, suit: .hearts),
            Card(rank: .queen, suit: .hearts),
            Card(rank: .king, suit: .hearts),
            Card(rank: .king, suit: .hearts),
            Card(rank: .ace, suit: .hearts)
        ]
        var stats = StatsDictionary()
        let stat = Stat(dateFinished: Date.now, won: true, initialLayout: Layout(), movesCount: 1, timeTaken: 1)
        var layout = Layout()
        layout.columns[0].cards = [deck.cardsToDeal[1]]
        stats[layout.tableauDescription] = stat
        layout.columns[0].cards = [deck.cardsToDeal[2]]
        stats[layout.tableauDescription] = stat
        self.stats.stats = stats
        // this is not the test! this part is basically just a repetition of the preceding test
        let result = await subject.newDeal()
        #expect(deck.methodsCalled == ["shuffle()", "deal()"])
        var expected = Layout()
        expected.columns[0].cards = [Card(rank: .king, suit: .hearts)]
        #expect(result == expected)
        #expect(await subject.deals.contains(expected.tableauDescription))
        // okay, now THIS is the test; we've got "previous" deals in stats and previously generated by the subject
        deck.methodsCalled = []
        let realResult = await subject.newDeal()
        expected.columns[0].cards = [Card(rank: .ace, suit: .hearts)]
        #expect(realResult == expected)
        #expect(await subject.deals.contains(expected.tableauDescription))
        #expect(deck.methodsCalled == [
            "shuffle()", "deal()", // jack, already in stats
            "shuffle()", "deal()", // queen, already in stats
            "shuffle()", "deal()", // king, already in previous deals
            "shuffle()", "deal()", // king, already in previous deals
            "shuffle()", "deal()" // ace, got it at last
        ])
    }
}
